-- ============================================================
-- CIALÉ — Fase 2: Seed inicial
-- 3 categorías + los 12 productos actuales (data/products.ts)
-- Ejecutar DESPUÉS de schema.sql. Seguro de re-ejecutar.
-- ============================================================

insert into public.categories (id, label, sort_order) values
  ('dijes',     'Dijes',            1),
  ('marina',    'Colección Marina', 2),
  ('coleccion', 'Colección',        3)
on conflict (id) do nothing;

insert into public.products
  (id, category_id, name, description, price, image, gradient, tags, variants, sort_order)
values
  ('coral', 'marina', 'Coral',
   'Dije de coral marino auténtico, cada pieza con tonalidades únicas que recuerdan a las profundidades del océano.',
   50000, '/products/Coral.webp', 'from-orange-200 via-rose-100 to-amber-50',
   '{"dije","marino","coral"}',
   '[{"id":"coral-natural","name":"Coral Natural","color":"Coral","hex":"#E79C88"},{"id":"coral-rojo","name":"Coral Rojo","color":"Rojo","hex":"#C75B39"},{"id":"coral-rosado","name":"Coral Rosado","color":"Rosado","hex":"#F2B5A0"}]',
   1),
  ('aura-rosa', 'dijes', 'Aura Rosa',
   'Dije delicado con acabado en rosa empolvado. Una pieza suave y elegante, hecha a mano con dedicación.',
   50000, '/products/AuraRosa.webp', 'from-pink-200 via-rose-100 to-pink-50',
   '{"dije","rosa","delicado"}',
   '[{"id":"aura-rosa-oro","name":"Rosa Dorado","color":"Rosa","hex":"#E8D3C8"},{"id":"aura-rosa-plata","name":"Rosa Plata","color":"Plata","hex":"#C0C0C0"},{"id":"aura-rosa-oro-24k","name":"Rosa Oro 24K","color":"Oro","hex":"#D4AF37"}]',
   2),
  ('nemo', 'marina', 'Nemo',
   'Dije temático marino con acabado texturizado inspirado en las corrientes del océano.',
   50000, '/products/Nemo.webp', 'from-blue-200 via-cyan-100 to-teal-50',
   '{"dije","marino","texturizado"}',
   '[{"id":"nemo-plata","name":"Plata","color":"Plata","hex":"#C0C0C0"},{"id":"nemo-oro","name":"Oro","color":"Oro","hex":"#D4AF37"},{"id":"nemo-cobre","name":"Cobre","color":"Cobre","hex":"#B87333"}]',
   3),
  ('nacar', 'dijes', 'Nácar',
   'Dije de nácar natural con reflejos iridiscentes que cambian con la luz. Una pieza verdaderamente única.',
   50000, '/products/Nacar.webp', 'from-amber-50 via-rose-50 to-blue-50',
   '{"dije","nácar","iridiscente"}',
   '[{"id":"nacar-natural","name":"Nácar Natural","color":"Nácar","hex":"#F5E6D3"},{"id":"nacar-rosa","name":"Nácar Rosa","color":"Rosa","hex":"#F2C4C4"},{"id":"nacar-azul","name":"Nácar Azul","color":"Azul","hex":"#B8D4E3"}]',
   4),
  ('ohana', 'coleccion', 'Ohana',
   'Inspirado en la unión y la familia. ''Ohana significa familia, y la familia no te abandona jamás.''',
   50000, '/products/Ohana.webp', 'from-rose-200 via-orange-100 to-yellow-50',
   '{"dije","familia","unión"}',
   '[{"id":"ohana-oro","name":"Oro","color":"Oro","hex":"#D4AF37"},{"id":"ohana-plata","name":"Plata","color":"Plata","hex":"#C0C0C0"},{"id":"ohana-rosa","name":"Rosa Dorado","color":"Rosa","hex":"#E8D3C8"}]',
   5),
  ('lula', 'dijes', 'Lula',
   'Dije geométrico con líneas modernas y acabado artesanal. La fusión perfecta entre lo contemporáneo y lo hecho a mano.',
   50000, '/products/Lula.webp', 'from-stone-200 via-amber-50 to-stone-100',
   '{"dije","geométrico","moderno"}',
   '[{"id":"lula-negro","name":"Negro Mate","color":"Negro","hex":"#2D2926"},{"id":"lula-dorado","name":"Dorado","color":"Dorado","hex":"#D4AF37"},{"id":"lula-plata","name":"Plata","color":"Plata","hex":"#C0C0C0"}]',
   6),
  ('aurora', 'dijes', 'Aurora',
   'Dije con destellos de color y piedras translúcidas que capturan la luz del amanecer.',
   50000, '/products/Aurora.webp', 'from-violet-200 via-pink-100 to-amber-50',
   '{"dije","piedras","translúcido","destellos"}',
   '[{"id":"aurora-rosa","name":"Rosa Aurora","color":"Rosa","hex":"#F2B5D4"},{"id":"aurora-lila","name":"Lila","color":"Lila","hex":"#C8A2C8"},{"id":"aurora-dorado","name":"Dorado","color":"Dorado","hex":"#D4AF37"}]',
   7),
  ('maia', 'coleccion', 'Maia',
   'Collar con detalles sutiles y cuentas seleccionadas a mano. Cada cuenta cuenta una historia.',
   50000, '/products/Maia.webp', 'from-green-100 via-amber-50 to-rose-50',
   '{"collar","cuentas","detalles"}',
   '[{"id":"maia-salvia","name":"Salvia","color":"Salvia","hex":"#A3B18A"},{"id":"maia-arena","name":"Arena","color":"Arena","hex":"#E8D3C8"},{"id":"maia-coral","name":"Coral","color":"Coral","hex":"#E79C88"}]',
   8),
  ('cora', 'dijes', 'Cora',
   'Dije de corazón artesanal, hecho con amor y dedicación. El regalo perfecto para quien llevas en el corazón.',
   50000, '/products/Cora.webp', 'from-rose-200 via-red-100 to-pink-50',
   '{"dije","corazón","amor"}',
   '[{"id":"cora-rosa","name":"Rosa","color":"Rosa","hex":"#E79C88"},{"id":"cora-rojo","name":"Rojo","color":"Rojo","hex":"#C75B39"},{"id":"cora-oro","name":"Dorado","color":"Oro","hex":"#D4AF37"}]',
   9),
  ('margot', 'coleccion', 'Margot',
   'Collar clásico elegante con acentos brillantes. Para quienes aprecian el lujo en los detalles.',
   50000, '/products/Margot.webp', 'from-gray-100 via-amber-50 to-gray-50',
   '{"collar","clásico","elegante","brillantes"}',
   '[{"id":"margot-plata","name":"Plata","color":"Plata","hex":"#C0C0C0"},{"id":"margot-oro","name":"Oro","color":"Oro","hex":"#D4AF37"},{"id":"margot-rosegold","name":"Rose Gold","color":"Rosa","hex":"#E8D3C8"}]',
   10),
  ('greta', 'dijes', 'Greta',
   'Dije vintage chic con engaste artesanal. Inspirado en la elegancia atemporal de las épocas pasadas.',
   50000, '/products/Greta.webp', 'from-amber-200 via-orange-100 to-yellow-50',
   '{"dije","vintage","chic","engaste"}',
   '[{"id":"greta-antiguo","name":"Oro Antiguo","color":"Antiguo","hex":"#B8860B"},{"id":"greta-plata","name":"Plata Vieja","color":"Plata","hex":"#A9A9A9"},{"id":"greta-cobre","name":"Cobre","color":"Cobre","hex":"#B87333"}]',
   11),
  ('elle', 'coleccion', 'Elle',
   'Collar minimalista contemporáneo. Menos es más: una pieza limpia y sofisticada para el día a día.',
   50000, '/products/Elle.webp', 'from-stone-100 via-stone-50 to-white',
   '{"collar","minimalista","contemporáneo"}',
   '[{"id":"elle-plata","name":"Plata","color":"Plata","hex":"#C0C0C0"},{"id":"elle-oro","name":"Dorado","color":"Oro","hex":"#D4AF37"},{"id":"elle-rosa","name":"Rose Gold","color":"Rosa","hex":"#E8D3C8"}]',
   12)
on conflict (id) do nothing;
